spring:
  application:
    name: bookstore2be
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookstore2
    username: root
    password: root
  session:
    timeout: 86400

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # ????

server:
  port: 5000
